version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Map container's port 5000 to host's port 5000
    volumes:
      - .:/app # Mount the current directory to the container
    environment:
      - FLASK_ENV=production
    restart: always
