version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Map container port 4000 to host port 4000
    environment:
      - FLASK_ENV=production
      - PORT=4000 # Optional: if your Flask app reads the port from environment variables
    restart: always
