[phases.setup]
# Install Python and Pip explicitly
commands = [
  "apt-get update && apt-get install -y python3 python3-pip",
  "pip3 install -r requirements.txt"
]

[phases.start]
commands = ["gunicorn -w 4 main:app"]
